services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=98204096
      - MYSQL_DATABASE=picpay
      - MYSQL_ROOT_PASSWORD=98204096
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: